let colorList = [
    'orange', 
    'red', 
    'green', 
    'blue', 
    'cadetblue', 
    'gray', 
    'lightcoral',
    'purple',  
    'pink', 
    'lightblue', 
    'blueviolet', 
    'aqua', 
    'darkcyan', 
    'darkgoldenrod', 
    'darkblue', 
    'darkmagenta', 
    'darkolivegreen', 
    'darkorchid', 
    'indianred', 
    'darkseagreen', 
    'darkslateblue', 
    'darkslategray', 
    'dodgerblue', 
    'firebrick', 
    'gold', 
    'hotpink', 
    'goldenrod'
];

export default colorList